<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="HaltedToReadyProgramTransition" Id="{c0f0f0a2-cf93-4506-8c61-280a7dac2cf6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT HaltedToReadyProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{fcb8a91d-6115-436e-9005-ca813e12e39c}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{2d3743fb-8f36-4ae2-b15c-415fe24cfa98}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := 'Reset';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{82d04b52-6282-4d76-9688-0c8a6775f22e}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{20b257b9-be39-4125-a237-93f9ce547f37}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Halted';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{361c2321-6059-4d60-a033-35d3c099d62e}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{17aa131d-526d-4dc4-8baf-8a39d0f5b4fc}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'HaltedToReady';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{86e0f4f1-67ec-4d6a-9a72-d9e4a721c180}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{1e1513e5-8d9b-4d68-951b-0a1d77fe5826}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Ready';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>