<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ReadyToRunningProgramTransition" Id="{c0923131-4e73-49f5-8f24-ecc07a3fece1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT ReadyToRunningProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{b30567bc-29ab-4456-99ef-ded7918d311f}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{646811fc-4a62-4ebd-9fe1-f0e9dddb079b}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := 'Start';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{146cf823-f365-42ba-922e-f7f37711b5a8}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{e10dc547-1a54-428a-8d9c-e19f3030729c}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Ready';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{2db5a2c9-5486-45f3-b943-f8d2997efcc4}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{a86c1746-283b-415f-9505-de2f02832320}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'ReadyToRunning';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{ca8db745-770e-466a-a2b0-f9cb7f674891}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{fed575fd-8433-4df7-90ab-4f99db554dd7}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Running';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>