<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ReadyToHaltedProgramTransition" Id="{01973c2d-b112-4650-be4a-f9396f7ef816}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT ReadyToHaltedProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{f5cd98a0-de67-44ed-aad0-15f236e45407}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{a70bb77b-cda4-4925-8cd7-1773879fa5c3}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := '';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{887453e9-6943-4b48-acfe-ffe935677f12}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{baca79cd-4684-4ee2-a622-d3c2f266c55d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := '';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{9db7f3c8-cd93-497e-82eb-faa872245fc7}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{120b0bfc-b02d-49af-b707-0f93a1ab7f5d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'ReadyToHalted';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{5b14bf5a-6b59-428d-b6a4-5e71b9a2e77d}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{5581b3f9-3ee2-4c32-980d-fc7a7767f5d0}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Halted';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>