<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="RunningToHaltedProgramTransition" Id="{8a6734b4-3b9e-42db-8f8f-8ed9038de12d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT RunningToHaltedProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{9ce43ec7-8a88-4a6a-ae50-c578da3da785}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{f71d1651-79fa-49fd-836b-b1342ffcf471}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := 'Halt';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{5920b324-7b3d-4765-b17f-c5375d0a1800}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{42e3645d-6610-4221-ad79-fe44ccb91ee8}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Running';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{5bf2e8bf-beb8-4504-862f-50899bc78b22}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{09de0d78-62ca-45fd-ae9b-4b4efcc46fae}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'RunningToHalted';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{bc3b59ab-11a2-47c7-9789-b60431e7b912}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{a99a9f8e-182e-4180-b2e1-268fb173d262}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Halted';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>