<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="RunningToSuspendedProgramTransition" Id="{3bf80ba6-d3f7-4a1c-8d5e-86a1c9d2884d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT RunningToSuspendedProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{c6c5af57-8fbe-4a3f-b175-e096658aa45c}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{12b06b64-c919-4f4e-8934-dfe7ba346f2a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := 'Suspend';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{432a791b-9550-475f-bc9c-f468c9eb5f4d}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{84047a41-525f-4156-ad0e-da3d3100038d}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Running';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{48f81495-8a8a-4e52-9fa6-bac58d18e600}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{4664638d-52c0-45f6-8db3-0d0a8d705d78}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'RunningToSuspended';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{0e57711f-03ea-4081-9509-8c979d28dd33}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{6981d00d-9e9c-4d05-aac4-24eedaf84274}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Suspended';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>