<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="RunningToReadyProgramTransition" Id="{9399d7ea-de5c-45b7-8cd0-0acca98d6354}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT RunningToReadyProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{891d0e19-b0cb-46a6-a6d3-e9f5e8102a63}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{8aeb8ca6-1084-4abe-bcb4-86915a1e9e23}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := '';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{13dbf4e9-59ca-47fc-8068-7989344a92f9}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{54ff4497-589c-4d00-8f96-35709db8ff1c}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Running';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{82d3c20d-03ab-4656-9dff-82bd58ebe9dc}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{fc4c335b-b334-48c3-bb53-cabc03bd9c5f}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'RunningToReady';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{9918d460-f2fe-4b07-9e0c-1afc0b84c67d}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{93307f72-c96a-4c12-a18e-f533426187cd}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Ready';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>