<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SuspendedToHaltedProgramTransition" Id="{f5f33ea2-6f16-4a7d-80ec-4312011d3e77}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT SuspendedToHaltedProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{c77a0b6d-83a6-4d0f-96c7-df2b39796874}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{1ca4689c-4cc4-428d-a96b-5a61ef43be71}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := 'Halt';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{154351a2-598a-4551-b24f-5b672ac811a1}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{a1607fcd-9e35-4ba2-a8e8-3a78549c0b0a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Suspended';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{164f540b-7deb-4e68-8903-d726f52dd894}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{090f3d2b-9ab1-403f-9cf5-6bc32c269395}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'SuspendedToHalted';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{9f60449a-d088-4d66-a3fb-9e0b099970be}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{b7974e80-10cc-4c34-bce0-092640d8d58e}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Halted';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>