<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SuspendedToReadyProgramTransition" Id="{dc74d145-21a0-4551-9761-225af06dd512}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT SuspendedToReadyProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{d4acb4ef-a083-4cfd-bd16-672ecc6b1b22}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{952b5430-3c5a-4073-b6be-7809ca8a6ef3}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := 'Reset';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{a4344b52-65f8-48af-a16f-3568d81b72d0}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{54c7a6e2-a226-48bb-81ef-f85153058fe4}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Suspended';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{36209df9-4a93-4223-9823-60c827646282}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{be7d2b31-d759-4c8c-b077-285414ba23f7}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'SuspendedToReady';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{b3c7346d-e5d4-4fd1-9a26-79f624325f4e}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{ede6727f-1bf6-497c-b811-771d313243fb}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Ready';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>