<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SuspendedToRunningProgramTransition" Id="{73940194-7ad8-4c7d-a7e2-da1428f97644}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT SuspendedToRunningProgramTransition EXTENDS ProgramTransition]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Cause" Id="{ec67baad-38fa-4640-8208-d6128403e7e1}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Cause : STRING]]></Declaration>
      <Get Name="Get" Id="{e08ff649-ce46-45f2-9356-6276d8c10e23}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Cause := 'Resume';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="FromState" Id="{d1f509d5-af93-4d5e-8ccd-7894ed258be1}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL FromState : STRING]]></Declaration>
      <Get Name="Get" Id="{570c370a-360d-44d6-b150-88b41d7add70}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[FromState := 'Suspended';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Name" Id="{c921389e-abd5-45b8-8f55-61d3bcc6517d}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{ed24db42-7c6b-4ead-b497-3d0ad090ef8a}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'SuspendedToRunning';]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ToState" Id="{400fb345-b0a6-442f-8b22-729b539e3211}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL ToState : STRING]]></Declaration>
      <Get Name="Get" Id="{a0edc4d5-eb6b-4a88-87ad-1896bee5c5bc}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[ToState := 'Running';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>