<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="UnifiedProgramExecutedStepAction" Id="{a15ca3f8-d428-4e90-bc82-1f3b00d1c74d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT UnifiedProgramExecutedStepAction EXTENDS ToolkitObject
VAR
	{attribute 'OPC.UA.DA' := '0'}
	_ClassName : STRING := __POUNAME();
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Decode" Id="{9ecd7e77-3788-4f58-92cf-f5296c35d2ff}">
      <Declaration><![CDATA[METHOD ABSTRACT Decode : BOOL
VAR_INPUT
	actionIndex : INT; 
	stepAction : REFERENCE TO UNIFIED_PROGRAM_STEP_ACTION;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>