<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="UnifiedProgramExecutedStepHelper" Id="{49ee27e1-9cec-4fc8-a263-6bffa370cd51}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM UnifiedProgramExecutedStepHelper
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="CreateActionInstance" Id="{cc7bc1ed-d7e0-423e-920d-b0be6e30f3f3}">
      <Declaration><![CDATA[METHOD CreateActionInstance : POINTER TO UnifiedProgramExecutedStepAction
VAR_INPUT
	actionName : STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="CreateTransitionConditionInstance" Id="{72f973d1-31dd-43c7-8dd1-d53833fd3a5f}">
      <Declaration><![CDATA[METHOD CreateTransitionConditionInstance : POINTER TO UnifiedProgramExecutedStepTransitionCondition
VAR_INPUT
	conditionName : STRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>