<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="UnifiedProgramExecutedStepTransitionCondition" Id="{74bb4b1e-360e-4087-9213-4d561ae08d05}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT UnifiedProgramExecutedStepTransitionCondition EXTENDS ToolkitObject
VAR
	{attribute 'OPC.UA.DA' := '0'}
	_ClassName : STRING := __POUNAME();
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Decode" Id="{6e70744a-4939-4e9d-a4d5-bd97e10c62b2}">
      <Declaration><![CDATA[METHOD ABSTRACT Decode : BOOL
VAR_INPUT
	transitionIndex : INT; 
	stepTransition : REFERENCE TO UNIFIED_PROGRAM_STEP_TRANSITION;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>