<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="OpcUaRequestItem" Id="{200666ba-908b-472f-8c22-3b6d239e05af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT OpcUaRequestItem EXTENDS TC.ToolkitObject
VAR
	_ConnectionHandle : DWORD;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="GetHandle" Id="{805f5ab9-be9e-4e41-b4ea-701990c1f4fa}">
      <Declaration><![CDATA[METHOD ABSTRACT GetHandle : OPC_UA_ACTION_EXECUTION_STATE
VAR_INPUT
	connectionHandle : DWORD;
END_VAR
VAR_OUTPUT
	exception : Exception;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="PerformAction" Id="{a12b7ee3-b79d-445f-9ad0-7179931cf62e}">
      <Declaration><![CDATA[METHOD ABSTRACT PerformAction : OPC_UA_ACTION_EXECUTION_STATE
VAR_OUTPUT
	exception : Exception;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ReleaseHandle" Id="{3ff0446a-2f58-4162-96ed-d000835983a0}">
      <Declaration><![CDATA[METHOD ABSTRACT ReleaseHandle : OPC_UA_ACTION_EXECUTION_STATE
VAR_OUTPUT
	exception : Exception;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Reset" Id="{c5f8ea59-0268-4c4a-a1c2-551dd982ac25}">
      <Declaration><![CDATA[METHOD ABSTRACT Reset ]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ResetAction" Id="{5fd04d9a-1dea-46bb-9f6e-0666366f1d1d}">
      <Declaration><![CDATA[METHOD ABSTRACT ResetAction ]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetNamespaceIndexForNamespaceUri" Id="{c5a5d65d-1db4-4820-ba1f-dfb2ee3f577a}">
      <Declaration><![CDATA[METHOD ABSTRACT SetNamespaceIndexForNamespaceUri
VAR_INPUT
	namespaceUri : STRING(Tc2_System.MAX_STRING_LENGTH);
	namespaceIndex : UINT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="OpcUaRequestItem">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="OpcUaRequestItem.GetHandle">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="OpcUaRequestItem.PerformAction">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="OpcUaRequestItem.ReleaseHandle">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="OpcUaRequestItem.Reset">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="OpcUaRequestItem.ResetAction">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="OpcUaRequestItem.SetNamespaceIndexForNamespaceUri">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>