<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="HaltedProgramState" Id="{a9eee460-5125-4d00-bef3-ce2985ca3212}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT HaltedProgramState EXTENDS ProgramState]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{b967a08b-8ec4-45ba-b5b7-013ea0ce9029}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{4c0e5d56-7101-4ea9-9d8c-2247c5aebe86}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'Halted';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>