<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ReadyProgramState" Id="{a809a80e-4ede-428a-bcc8-804e808d41fe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT ReadyProgramState EXTENDS ProgramState]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{2eafe4a6-8d61-4fbc-8e35-2d7997fb97f6}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{8d0105fe-43f6-483a-b829-b6f743afeeb4}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'Ready';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>