<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="RunningProgramState" Id="{9c9f25b8-88d5-4d9f-95d2-e187fffc78c8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT RunningProgramState EXTENDS ProgramState]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{62c20930-e33d-49fe-970d-a9da268660ee}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{248a9be7-cc06-458d-b07d-65abc8d73e3b}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'Running';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>