<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="SuspendedProgramState" Id="{44690efb-abcd-486a-acbb-08acdab2a352}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT SuspendedProgramState EXTENDS ProgramState]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Name" Id="{930130f5-7e88-4946-8fab-d91419aa18d5}">
      <Declaration><![CDATA[{attribute 'monitoring' := 'call'}
{attribute 'OPC.UA.DA.Property' := '1'}
{attribute 'OPC.UA.DA.Access' := '1'}
PROPERTY FINAL Name : STRING]]></Declaration>
      <Get Name="Get" Id="{e232729c-09b7-491b-9a90-95bb9852b556}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := 'Suspended';]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>