<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CommunicationSettings" Id="{e05e7971-f90f-4e84-a2e2-8680d10b5b1e}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT CommunicationSettings
VAR_INPUT
	DefaultOperationTimeout : TIME := Tc2_System.DEFAULT_ADS_TIMEOUT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="CommunicationTypeName" Id="{55c07768-0d4b-4381-b100-780dd7a23e81}">
      <Declaration><![CDATA[PROPERTY ABSTRACT CommunicationTypeName : STRING]]></Declaration>
      <Get Name="Get" Id="{948df464-6698-47f0-b35b-261586637032}">
        <Declaration><![CDATA[]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="CommunicationSettings">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CommunicationSettings.CommunicationTypeName.Get">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>